import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img:'https://s4sassy.com/ibaweb/pub/media/catalog/product/_/9/_9d1104-903407-min-fl-1477c_371_2.jpg',
    desc:'Bimba Floral Printed Indian Kurtis For Women Anarkali Kurti',
    original_price:1000,
    price: 500,
    categoryName: "women",
    rating:3.9,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/51oE5MBmb9L._UL1050_.jpg',
    desc:'Cotton Straight Kurta with Pant',
    original_price:2599,
    price: 469 ,
    categoryName: "women",
    rating:3.7,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/51pQgAd2W4L._UX679_.jpg',
    desc:'FabAlley Women Western Top',
    original_price:1600,
    price:640 ,
    categoryName: "women",
    rating:3.6,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/71iD+LE4wBL._UY879_.jpg',
    desc:'Cotton Printed Flared Top',
    original_price:2299,
    price: 789,
    categoryName: "women",
    rating: 4.1,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/61Q1QkDd86L._UY879_.jpg',
    desc:'Printed Georgette Chikankari Embroidered Kurti ',
    original_price: 2599,
    price: 1000,
    categoryName: "women",
    rating:4.5,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/61uUqjg3r-L._UX569_.jpg',
    desc:'Fashion Top with Short Sleeves & Elastic Waist',
    original_price:1199,
    price:526 ,
    categoryName: "women",
    rating:3.9,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/81bWRBJ3rUL._AC_UL600_FMwebp_QL65_.jpg',
    desc:'Slim Fit Shirt',
    original_price:2599,
    price: 1299,
    categoryName: "men",
    rating:3.9,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/71AvydIc4jL._AC_UL600_FMwebp_QL65_.jpg',
    desc:'Arrow Newyork Men Wine Mitered Cuff Patterned Formal Shirt',
    original_price:1199,
    price: 550,
    categoryName: "men",
    rating: 3.4,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/61QfplyCfXL._UY741_.jpg',
    desc:'Mens Cotton Half Sleeve Striped Round Neck T Shirt',
    original_price:1499,
    price: 569,
    categoryName: "men",
    rating:3.9,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/41aIRinpsEL.jpg',
    desc:'Donald Duck Stay in Bed Round Neck Mens and Boys T-Shirt',
    original_price:2000,
    price:1000 ,
    categoryName: "men",
    rating:4.0,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/81efMvzQeNL._UX569_.jpg',
    desc:'Symbol Men Formal Shirt',
    original_price:2199,
    price: 450,
    categoryName: "men",
    rating:3.8,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/61JVTMD+vQS._UY879_.jpg',
    desc:'Hugsy Mens Graphic Printed Cotton T-Shirt',
    original_price:999,
    price: 734,
    categoryName: "men",
    rating:4.1,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/81OIDieRpQL._UY879_.jpg',
    desc:'Denim Girls Dress ',
    original_price:1599,
    price: 799,
    categoryName: "kids",
    rating:3.4,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/51YB2gfh9sL._UX679_.jpg',
    desc:'Boys Cotton Stripes Bear Print Half Sleeves T-Shirt and Pant Set',
    original_price:1009,
    price:540 ,
    categoryName: "kids",
    rating:3.5,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/41p8UlsDbVL.jpg',
    desc:'Printed Full Sleeve Shirt with Plaid Waistcoat Bowtie and Pant ',
    original_price:2999,
    price: 839,
    categoryName: "kids",
    rating:4.0,
  },
  {
    _id: uuid(),
    img:'https://m.media-amazon.com/images/I/71SmA11DSTL._UX679_.jpg',
    desc:'Girls Cotton Full Sleeves Polka Dots Printed Casual Dress',
    original_price:1499,
    price:900 ,
    categoryName: "kids",
    rating:3.7,
  },
  
];
