import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71o5VToIacL._UY741_.jpg",
    desc: "Bimba Floral Printed Indian Kurtis For Women Anarkali Kurti",
    name:"floral kurta",
    original_price: 1100,
    price: 500,
    categoryName: "women",
    rating: 3.9,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51oE5MBmb9L._UL1050_.jpg",
    desc: "Cotton Straight Kurta with Pant",
    name:"straight kurta",
    original_price: 2599,
    price: 469,
    categoryName: "women",
    rating: 3.7,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51pQgAd2W4L._UX679_.jpg",
    desc: "FabAlley Women Western Top",
    name:"top",
    original_price: 1600,
    price: 640,
    categoryName: "women",
    rating: 3.6,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71iD+LE4wBL._UY879_.jpg",
    desc: "Cotton Printed Flared Top",
    name:"printed top",
    original_price: 2299,
    price: 789,
    categoryName: "women",
    rating: 4.1,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61Q1QkDd86L._UY879_.jpg",
    desc: "Printed Georgette Chikankari Embroidered Kurti ",
    name:"chikankari kurta",
    original_price: 2599,
    price: 1000,
    categoryName: "women",
    rating: 4.5,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61uUqjg3r-L._UX569_.jpg",
    desc: "Fashion Top with Short Sleeves & Elastic Waist",
    name:"top",
    original_price: 1199,
    price: 526,
    categoryName: "women",
    rating: 3.9,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81bWRBJ3rUL._AC_UL600_FMwebp_QL65_.jpg",
    desc: "Slim Fit Shirt",
    name:"slim fit shirt",
    original_price: 2599,
    price: 1299,
    categoryName: "men",
    rating: 3.9,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71AvydIc4jL._AC_UL600_FMwebp_QL65_.jpg",
    desc: "Arrow Newyork Men Wine Mitered Cuff Patterned Formal Shirt",
    name:"formal shirt",
    original_price: 1199,
    price: 550,
    categoryName: "men",
    rating: 3.4,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61QfplyCfXL._UY741_.jpg",
    desc: "Mens Cotton Half Sleeve Striped Round Neck T Shirt",
    name:"round t-shirt",
    original_price: 1499,
    price: 569,
    categoryName: "men",
    rating: 3.9,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/41aIRinpsEL.jpg",
    desc: "Donald Duck Stay in Bed Round Neck Mens and Boys T-Shirt",
    name:"t-shirt",
    original_price: 2000,
    price: 1300,
    categoryName: "men",
    rating: 4.0,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/81efMvzQeNL._UX569_.jpg",
    desc: "Symbol Men Formal Shirt",
    name:"formal shirt",
    original_price: 2199,
    price: 450,
    categoryName: "men",
    rating: '3.8',
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/61JVTMD+vQS._UY879_.jpg",
    desc: "Hugsy Mens Graphic Printed Cotton T-Shirt",
    name:"cotton t-shirt",
    original_price: 999,
    price: 734,
    categoryName: "men",
    rating: 4.1,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/610Yg-SPgcL._UY741_.jpg",
    desc: "Naughty Ninos  Knee-Length Dress ",
    name:"knee-length frock",
    original_price: 1599,
    price: 799,
    categoryName: "kids",
    rating: 3.4,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51OsCiPvLwL._UX569_.jpg",
    desc: "Unicorn Net Frock with Rainbow Flare Dress ",
    name:"flared frock",
    original_price: 1009,
    price: 540,
    categoryName: "kids",
    rating: 3.5,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/71y8vLQqklL._UY879_.jpg",
    desc: "Kids Ethnic Cotton Silk Blend Nehru Modi Jacket Kurta & Pyjama Set",
    name:"kurta pyjama",
    original_price: 2999,
    price: 839,
    categoryName: "kids",
    rating: 4.0,
  },
  {
    _id: uuid(),
    img: "https://m.media-amazon.com/images/I/51a6JdmMeTL._UY879_.jpg",
    desc: " Printed Hoisery Cotton T shirt & Short Set",
    name:"shorts",
    original_price: 1499,
    price: 900,
    categoryName: "kids",
    rating: 3.7,
  },
];
